plugins {
    alias(libs.plugins.spring.boot)
    alias(libs.plugins.spring.dependency.management)
    id 'java'
}

group = 'ru.otus.msaa'
version = '1.0-SNAPSHOT'

dependencies {
    implementation libs.spring.boot.starter.web
    implementation libs.spring.boot.starter.security
    implementation libs.spring.boot.starter.oauth2.resource.server
    
    testImplementation libs.spring.boot.starter.test
}

tasks.named('test') {
    useJUnitPlatform()
}
